#!/usr/bin/env python

'''
Use docker container 's php to compile php code
'''

import os
import sys
import subprocess

# PWD = os.environ['PWD']
PWD = os.getcwd()
CMD = '/usr/bin/docker exec phpfpmcompiler_php_1 sh -c '
CMD = CMD + "'cd " + PWD + ' && php'

lenArgv = len(sys.argv)
if lenArgv < 1:
  exit()

if lenArgv == 3:
  if sys.argv[1] == '-r':
    CMD = CMD + ' -r "' + sys.argv[2] + '"'
else:
  for i in range(1, lenArgv):
    CMD = CMD + ' ' + sys.argv[i]

CMD = CMD + "'"

# print(CMD)

subprocess.call(CMD, shell=True)
