#!/usr/bin/env python

import os
import sys
import subprocess

PHP_CONTAINER = 'phpfpmcompiler_php_1'

PWD = os.getcwd()
CMD = [
    '/usr/bin/docker',
    'exec',
    '--workdir='+PWD,
    PHP_CONTAINER,
    'php'
]

subprocess.call(CMD + sys.argv[1:])

